data:
  data_src: dataset.csv
  batch_size: 12
  pin_memory: true
  num_workers: 2

model:
  convolution_count: 4
  convolution_algorithm: GraphConv 
  input_dimension: 247

trainer:
  max_epochs: 30
  gpus: null

defaults:
  - features: degree
  - logger: wandb
