data:
  train_dir: /content/data2
  test_dir: /content/test2
  batch_size: 12
  pin_memory: true
  num_workers: 2
  split_train_val: false
  split_ratios: [0.8, 0.2]  

model:
  convolution_count: 4
  convolution_algorithm: GraphConv 
  input_dimension: 247

trainer:
  max_epochs: 30
  gpus: null

defaults:
  - features: degree
  - logger: wandb
