data:
  train_dir: /content/data2
  test_dir: /content/test2
  batch_size: 16
  pin_memory: false
  num_workers: 6
  split_train_val: true
  split_ratios: [0.75, 0.25]
  consider_features: method_summary

model:
  convolution_count: 0
  convolution_algorithm: GraphConv 
  input_dimension: 128

trainer:
  max_epochs: 100
  gpus: null

defaults:
  - features: degree
  - logger: wandb
